apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jaromir-eks
  region: eu-central-1

managedNodeGroups:
  - name: managed-ng-4
    minSize: 1
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: true
    labels: {role: worker}
    tags:
      nodegroup-role: worker
      #instanceType: m5.8xlarge
    availabilityZones: ['eu-central-1a']
