apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hazelcast
spec:
  replicas: 1
  serviceName: hazelcast
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      serviceAccountName: hazelcast-service-account
      containers:
        - name: hazelcast
          image: hazelcast/hazelcast:4.1
          ports:
          - containerPort: 5701
          env:
          - name: JAVA_OPTS
            value: "-Dhazelcast.config=/data/hazelcast/configuration/hazelcast-config.yaml"
          volumeMounts:
          - name: hazelcast-configuration
            mountPath: /data/hazelcast/configuration
      volumes:
      - name: hazelcast-configuration
        configMap:
          name: hazelcast-configuration
